@api = http://localhost:3003/products

### GET
GET {{api}}

### GET BY ID
GET {{api}}/12

### COUNT
GET {{api}}/count

### POST
POST {{api}}
Content-Type: application/json

{
    "name": "product 15", 
    "description": "product 15 description",
    "quantity": "201"
}

### DELETE
DELETE  {{api}}/11

### UPDATE
PUT {{api}}/12
Content-Type: application/json

{
    "name": "Laptop HP",
    "description": "Gaming Latop HP",
    "quantity": 300
}





