@api = http://localhost:3003/products

### GET
GET {{api}}

### GET BY ID
GET {{api}}/2

### POST
POST {{api}}
Content-Type: application/json

{
    "name": "product 12", 
    "description": "product 12 description",
    "quantity": "201"
}
