@api = http://localhost:3003/products

### GET
GET {{api}}

### GET BY ID
GET {{api}}/12

### COUNT
GET {{api}}/count

### POST
POST {{api}}
Content-Type: application/json

{
    "name": "product 16", 
    "description": "product 16 description",
    "quantity": "200"
}

### DELETE
DELETE  {{api}}/6

### UPDATE
PUT {{api}}/12
Content-Type: application/json

{
    "name": "Laptop HP",
    "description": "Gaming Latop HP",
    "quantity": 100
}





